### 1. Read Documention of [torch.tensor](https://docs.pytorch.org/docs/stable/tensors.html#torch-tensor) and [torch.cuda](https://docs.pytorch.org/docs/stable/cuda.html#module-torch.cuda)

### 2. Create a random tensor with shape (7, 7).

In [ ]:
import torch
TENSOR0 = torch.rand(size=[7,7],device='cpu')
TENSOR0,TENSOR0.shape,TENSOR0.ndim

(tensor([[0.5600, 0.3772, 0.0015, 0.1387, 0.3394, 0.6116, 0.8483],
         [0.0759, 0.3035, 0.3075, 0.1199, 0.1108, 0.4528, 0.6958],
         [0.0155, 0.6441, 0.3056, 0.7306, 0.5607, 0.3553, 0.3286],
         [0.9932, 0.0524, 0.9683, 0.1408, 0.8828, 0.8016, 0.7896],
         [0.0997, 0.5600, 0.7954, 0.2554, 0.5546, 0.0351, 0.2311],
         [0.7344, 0.6030, 0.7216, 0.3996, 0.3997, 0.8241, 0.6125],
         [0.9665, 0.2451, 0.5411, 0.8686, 0.2132, 0.5532, 0.6511]]),
 torch.Size([7, 7]),
 2)

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [ ]:
TENSOR1 = torch.rand(size=[1,7])
tensor_matmul = torch.matmul(TENSOR0,TENSOR1.T)
tensor_matmul

tensor([[2.0862],
        [1.5783],
        [1.7206],
        [3.0786],
        [1.3690],
        [2.9736],
        [2.9069]])

### 4. Set the random seed to 0 and do 2 & 3 over again.

In [ ]:

torch.manual_seed(0)
tensor1 = torch.rand([7,7])
tensor2 = torch.rand([1,7])
tensor3 = torch.matmul(tensor1,tensor2.T)
print(tensor3)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5 Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [68]:
torch.cuda.manual_seed(1234)

### 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [73]:
tensor1 = torch.rand([2,3],device='cuda')
tensor2 = torch.rand([2,3],device='cuda')
torch.manual_seed(1234)
tensor3 = torch.matmul(tensor1,tensor2.T)
tensor1,tensor2,tensor3

(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.6208, 0.0276, 0.3255],
         [0.1114, 0.6812, 0.3608]], device='cuda:0'),
 tensor([[0.2786, 0.7668],
         [0.7343, 0.6102]], device='cuda:0'))

### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [75]:
tensor2 = torch.reshape(tensor2,[3,2])
tensor3 = torch.matmul(tensor1,tensor2)
tensor3,tensor3.shape

(tensor([[0.7154, 0.2908],
         [1.1616, 0.3998]], device='cuda:0'),
 torch.Size([2, 2]))

In [77]:
torch.max(tensor3),torch.min(tensor3)

(tensor(1.1616, device='cuda:0'), tensor(0.2908, device='cuda:0'))

In [78]:
torch.argmax(tensor3),torch.argmin(tensor3)

(tensor(2, device='cuda:0'), tensor(1, device='cuda:0'))

10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [84]:
torch.manual_seed(7)
tensor4 = torch.rand([1,1,1,10])
tensor5 = torch.squeeze(tensor4)
tensor4,tensor4.shape,tensor5,tensor5.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))